#6 - 3 questions
rajrohanyadav/coding-solutions pull request #7
Opened 2023-09-25 16:00 UTC by niksvat

closes #6

2023-09-25 16:16 UTC, rajrohanyadav requested changes
Thanks @niksvat for creating PR.
Please add `<question-name>.txt` file in each of the folders along with URL to the questions.

2023-09-25 16:16 UTC, rajrohanyadav commented on solutions/count-good-node/Solution.java
filename should be `count-good-node.java`

2023-09-25 16:16 UTC, rajrohanyadav commented on solutions/lca/Solution.java
please use the complete question name, and update `Solution.java` as well accordingly.

2023-09-25 16:16 UTC, rajrohanyadav commented on solutions/validate-bst/Solution.java
the filename should be `validate-bst.java`.

2023-09-26 16:21 UTC, niksvat commented on solutions/count-good-node/Solution.java
Done.

2023-09-26 16:21 UTC, niksvat commented on solutions/lca/Solution.java
Done.

2023-09-26 16:21 UTC, niksvat commented on solutions/validate-bst/Solution.java
Done.

2023-09-26 16:25 UTC, rajrohanyadav approved these changes

2023-09-26 16:25 UTC, merged